sonar.host.url=http://localhost:9000
sonar.token=sqp_a1c9b7d4c46ba2598c48c9fcc757c2843f8f1577

sonar.projectKey=tingeso-frontend
sonar.projectName=tingeso-frontend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx
sonar.exclusions=node_modules/**,dist/**,src/vite-env.d.ts

sonar.sourceEncoding=UTF-8
sonar.javascript.environments=browser