services:
  db:
    image: mysql:lts
    environment:
      MYSQL_DATABASE: tingeso_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user_tingeso
      MYSQL_PASSWORD: pass_tingeso
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    restart: always
    command: start-dev --import-realm --http-port 7080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db:3306/tingeso_db
      KC_DB_USERNAME: user_tingeso
      KC_DB_PASSWORD: pass_tingeso
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: http://localhost:7080    # change localhost for server ip
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
    ports:
      - "7080:7080"
    volumes:
      - ./imports:/opt/keycloak/data/import
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/kc.sh", "show-config"]
      interval: 15s
      timeout: 5s
      retries: 15
      start_period: 60s
    networks:
      - backend-network

  backend1: &backend_config
    container_name: backend1
    hostname: backend1
    build: ./backend
    image: benjaminoq/ev-1-tingeso-backend
    restart: on-failure
    environment:
      PORT: 8080
      DB_URL: jdbc:mysql://db:3306/tingeso_db
      DB_USER: user_tingeso
      DB_PASSWORD: pass_tingeso
      KEYCLOAK_ISSUER_URI: http://localhost:7080/realms/tingeso-1-realm   # change localhost for server ip
      KEYCLOAK_JWK_SET_URI: http://keycloak:7080/realms/tingeso-1-realm/protocol/openid-connect/certs
      KEYCLOAK_CLIENT_ID: tingeso-1-backend
      KEYCLOAK_CLIENT_SECRET: Z5uuNMVdXMPEvzUkYm5jjwadC50gmakA
      TZ: America/Santiago
      ALLOWED_ORIGINS: http://localhost:8070,http://3.16.44.233,http://3.16.44.233:8070 # change for server ip
    expose:
      - "8080"
    networks:
      - backend-network
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  #  backend2:
  #    <<: *backend_config
  #    container_name: backend2
  #    hostname: backend2
  #
  #  backend3:
  #    <<: *backend_config
  #    container_name: backend3
  #    hostname: backend3

  frontend1: &frontend_config
    container_name: frontend1
    hostname: frontend1
    build:
      context: ./frontend
      args:
        VITE_BACKEND_SERVER: localhost  # change for server ip
        VITE_BACKEND_PORT: "8080"
        VITE_KEYCLOAK_SERVER: localhost  # change for server ip
        VITE_KEYCLOAK_PORT: "7080"
        VITE_KEYCLOAK_REALM: tingeso-1-realm
        VITE_KEYCLOAK_CLIENT_ID: tingeso-1-frontend
    image: benjaminoq/ev-1-tingeso-frontend
    restart: on-failure
    networks:
      - frontend-network
    depends_on:
      - nginx-backend
      - keycloak

  #  frontend2:
  #    <<: *frontend_config
  #    container_name: frontend2
  #    hostname: frontend2
  #
  #  frontend3:
  #    <<: *frontend_config
  #    container_name: frontend3
  #    hostname: frontend3

  nginx-backend:
    image: nginx:latest
    container_name: nginx-backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - backend1
  #      - backend2
  #      - backend3

  nginx-frontend:
    image: nginx:latest
    container_name: nginx-frontend
    restart: always
    ports:
      - "8070:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend-network
    depends_on:
      - frontend1
  #      - frontend2
  #      - frontend3

networks:
  frontend-network:
  backend-network:

volumes:
  db_data:
  keycloak_data: